import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { Toaster } from "@/components/ui/toaster"
import { ThemeProvider } from "@/components/providers/theme-provider";
import { NavBar } from "@/components/Nav/Nav-bar";
import Footer from "@/components/footer/footer";
import { AuthSessionProvider } from "@/components/providers/authProvider";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="">
      
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <AuthSessionProvider>
        <ThemeProvider
      attribute="class"
      defaultTheme="system"
      enableSystem
      disableTransitionOnChange
    >
      <NavBar/>
        {children}
        <Toaster />
        <Footer/>
        </ThemeProvider>
        </AuthSessionProvider>
    
      </body>
      
    </html>
  );
}
